# =============================================================================
# File        : rust-toolchain.toml
# Author      : yukimemi
# Last Change : 2024/03/31 14:51:37.
# =============================================================================

[toolchain]
channel = "nightly"
